sudo: false
language: python
dist: trusty

jobs:
  fast_finish: true
  include:

    # Macos is slow, only if everything has passed
    - stage: Macos - All Conan versions
      name: Conan Current - Python 2.7
      language: generic
      os: osx
      osx_image: xcode11.2
      env: PYVER=py27 TOXENV=py27-conancurrent

before_install:
  - ./.travis/before_install.sh

install:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
      pyenv activate conan;
    fi
  - pip install --upgrade pip
  - pip install tox tox-venv
  - pip install -r .travis/requirements_travis.txt

script:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
      pyenv activate conan
    fi
  - tox
